name: Assign review by comment

on: [issue_comment, pull_request_review]

jobs:
  assign_review_by_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Assign review by comment
        uses: cats-oss/github-action-auto-assign@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
