name: Text check by Textlint
on:
  push:
    branches: [main, master]
    paths:
      - 'entries/**.md'
  pull_request:
    branches: [main, master]
    paths:
      - 'entries/**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: v20.17.0

      - name: Package Install
        run: npm install

      - name: Exec Textlint
        run: |
          git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} \
            --diff-filter=AM \
            --name-only -- '*.md' \
            | xargs npm run lint
